### ISSUE TITLE
Generalize handling of concurrent writes during sync

### ISSUE THREAD

**Issue by ashvina** [onetable-io/onetable#14]
`OneTableClient` has logic to handle the case where archival has already kicked in on the source, which requires a snapshot sync instead of incremental to catch up to the active timeline. However the logic coupled to Hudi API and needed to be deactivated. This issue tracks enabling it such that it works for any format.

_Originally posted by @the-other-tim-brown in https://github.com/onetable-io/onetable/pull/9#discussion_r1323200675_

**Comment by vamshigv** [comment]
@the-other-tim-brown @ashvina this can be closed right?

**Comment by the-other-tim-brown** [comment]
Yes, marking as closed
