### ISSUE TITLE
All conversion paths tested

### ISSUE THREAD

**Issue by the-other-tim-brown** [onetable-io/onetable#23]
We should have a basic testing flows for:

1. Hudi -> Iceberg and Delta (already exists)
2. Iceberg -> Delta and Hudi
3. Delta -> Hudi and Iceberg

**Comment by the-other-tim-brown** [comment]
Will be covered in https://github.com/onetable-io/onetable/pull/219

**Comment by vamshigv** [comment]
done with last pr 219
