### ISSUE TITLE
Assistance Needed Installation " mvn clean package" Fails 

### ISSUE THREAD

**Issue by soumilshah1995** [onetable-io/onetable#241]
Hello I am trying to follow steps mentioned on website https://onetable.dev/docs/setup

##### Step 2: I have java 11 and man installed on Mac through home brew 

![Screenshot 2023-11-16 at 6 29 38 PM](https://github.com/onetable-io/onetable/assets/39345855/e17817eb-9d0f-48fc-af87-54f4aed7a08e)

![Screenshot 2023-11-16 at 6 29 52 PM](https://github.com/onetable-io/onetable/assets/39345855/97561ecc-107f-425f-a4f8-bc1dbb31961d)

```
mvn clean package
```

# Error 

![Screenshot 2023-11-16 at 6 31 29 PM](https://github.com/onetable-io/onetable/assets/39345855/75f5d045-255e-4db9-a270-c19f221b3b55)

![Screenshot 2023-11-16 at 6 32 02 PM](https://github.com/onetable-io/onetable/assets/39345855/9fa4d8fa-34e9-481d-9968-8b989914cbbf)

any help would be greatly appreciated or if you guys can provide direct link to jar file that would be great :D

**Comment by sagarlakshmipathy** [comment]
Hi @soumilshah1995 

Thanks for opening the issue. Can you confirm which branch you're on? I tried building a jar on `main` and was able to do so with `mvn clean package`.

For context:

```
sagarl@dev onetable % java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```
```
sagarl@dev onetable % mvn --version
Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: /Users/sagarl/Downloads/apache-maven-3.9.4
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
```
```
sagarl@dev onetable % git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
sagarl@dev onetable % 
```

**Comment by soumilshah1995** [comment]
@sagarlakshmipathy I am on main branch 


![Screenshot 2023-11-16 at 6 57 55 PM](https://github.com/onetable-io/onetable/assets/39345855/169343f9-f905-421c-800e-596de08e9c44)


"Could you please share the JAR file with me, possibly through a Google Drive link? I'm eager to explore OneTable and generate content for others. I would greatly appreciate your assistance in providing the JAR files. Thank you!"

**Comment by the-other-tim-brown** [comment]
@soumilshah1995 you can find the jars in the packages: https://github.com/onetable-io/onetable/packages/1986830 - you can use the bundled jar in the right hand side of the UI

**Comment by sagarlakshmipathy** [comment]
Tim's referring to

![image](https://github.com/onetable-io/onetable/assets/30472234/4d5efeb9-0914-4017-af6a-f8a97472d633)

You can then run sync using something like `java -jar ~/Downloads/utilities-0.1.0-beta1-bundled.jar --datasetConfig my_config.yaml`

**Comment by soumilshah1995** [comment]
Thanks a lot let me try  and play with it and open new issue if I see some weird error :D

**Comment by the-other-tim-brown** [comment]
@soumilshah1995 you have java version 21.0.1 set in your maven, we both have java 11 on our local. 
<img width="163" alt="image" src="https://github.com/onetable-io/onetable/assets/1360517/d4e7ed14-dedc-43de-937d-a76946e7d70f">
