### ISSUE TITLE
Build Issue with Netty io.netty:netty-tcnative-classes Dependency

### ISSUE THREAD

**Issue by lmccay** [onetable-io/onetable#285]
Build failure with the below failure. I was able to get past it build and tests complete successfully by adding it to the exclusion list for the Spark Core dependency. I can open a PR with that change but am curious whether others have seen the same and/or whether someone knows whether netty-tc-native-classes are needed.

It does appear to be included in the netty-all pom.xml as an explicit dependency so it should be fine to exclude here.
The same is done inside of the netty-all pom for the netty-handler then it is explicitly added as a dependency with the appropriate version to netty-all.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for onetable 0.1.0-SNAPSHOT:
[INFO] 
[INFO] onetable ........................................... SUCCESS [  1.097 s]
[INFO] api ................................................ SUCCESS [  4.518 s]
[INFO] hudi-support ....................................... SUCCESS [  0.020 s]
[INFO] hudi-utils ......................................... SUCCESS [  3.001 s]
[INFO] core ............................................... FAILURE [  0.633 s]
[INFO] utilities .......................................... SKIPPED
[INFO] hudi-extensions .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.371 s
[INFO] Finished at: 2023-12-09T00:26:27-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project onetable-core: Could not resolve dependencies for project io.onetable:onetable-core:jar:0.1.0-SNAPSHOT: Failed to collect dependencies at org.apache.spark:spark-core_2.12:jar:3.2.1 -> org.apache.spark:spark-network-common_2.12:jar:3.2.1 -> io.netty:netty-all:jar:4.1.74.Final -> io.netty:netty-tcnative-classes:jar:2.0.48.Final: Failed to read artifact descriptor for io.netty:netty-tcnative-classes:jar:2.0.48.Final: Could not transfer artifact io.netty:netty-tcnative-classes:pom:2.0.48.Final from/to central (https://repo.maven.apache.org/maven2): /home/lmccay/.m2/repository/io/netty/netty-tcnative-classes/2.0.48.Final/netty-tcnative-classes-2.0.48.Final.pom.part.lock (No such file or directory) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :onetable-core

**Comment by lmccay** [comment]
Okay, I've verified that the following class from the netty-tcnative-classes ends up in the ./utilities/target/utilities-0.1.0-SNAPSHOT-bundled.jar after packaging even with the exclusion.

I will open a PR to get the exclusion in.

**Comment by the-other-tim-brown** [comment]
@lmccay I haven't seen this issue before and the build is passing on CI where we also create that jar. Have you tried clearing that entry from your local maven cache (.m2 dir)? I'll take a look at your PR as well

**Comment by lmccay** [comment]
That does seem to have fixed it. Don't understand why that would be but I didn't understand why it wasn't working to begin with. I did have to sudo to clear it though - maybe it was a permissions issue from another build or something.

Ahh - that does seem to be it - here is an example...

rwxrwxr-x  6 lmccay lmccay 4096 Dec  8 23:20 netty-codec-stomp
drwxrwxr-x  6 lmccay lmccay 4096 Dec  8 23:20 netty-codec-xml
drwxrwxr-x 15 lmccay lmccay 4096 Dec  8 23:20 netty-common
drwxrwxr-x 14 lmccay lmccay 4096 Dec  8 23:20 netty-handler
drwxrwxr-x 10 lmccay lmccay 4096 Dec  8 23:20 netty-handler-proxy
drwxr-xr-x  3 root   root   4096 Dec 14  2022 netty-handler-ssl-ocsp
drwxrwxr-x 18 lmccay lmccay 4096 Dec  8 23:20 netty-parent
drwxrwxr-x 14 lmccay lmccay 4096 Dec  8 23:20 netty-resolver
drwxrwxr-x  9 lmccay lmccay 4096 Dec  8 23:20 netty-resolver-dns
drwxrwxr-x  6 lmccay lmccay 4096 Dec  8 23:20 netty-resolver-dns-classes-macos
drwxrwxr-x  6 lmccay lmccay 4096 Dec  8 23:20 netty-resolver-dns-native-macos

We must not be pulling in netty-handler-ssl-ocsp which is why it is working and now netty-tcnative-classes is lmccay which is why it is working.

We can ignore the PR though it does seem to be redundantly pulled from spark-core and netty-all anyway. Might run into version issues that way.

**Comment by the-other-tim-brown** [comment]
Ok can you mark the PR and this issue as closed if you think things are ok for now? If others report something similar we can spend some more time looking at it.
